#!/bin/bash


if [[ -e /tmp/dnscheck ]]; then

    clear
    /bin/dns-changer
    
else

    sudo cp /etc/resolv.conf /etc/dns/backup.conf
    echo done! >> /tmp/dnscheck
    clear
    /bin/dns-changer

fi